### ISSUE TITLE
Create AR Aging Report Prototype

### ISSUE THREAD

**Issue by Domokin** [Domokin/Benchmark#27]
- [x] Create AR Aging Report in Webi
- [x] Create BIMD Standard Style Template for Webi

**Comment by Johnsay1** [comment]
Since TX_ID is not available in the detail, when pulling in the outstanding AR by guarantor account, it throws an error for the outstanding amount if there are multiple transactions on the same post date. Will send examples via secure email. 

Age Over xx YN is also returning *Unknown on some accounts.

**Comment by Domokin** [comment]
Age Over xx YN has been resolved.  Issue was with where Age = 0.  TX_ID, TDL_ID has been added to the Universe as well.

**Comment by Domokin** [comment]
OHSU Template has been created and placed in the UMG Distribution folder for now, until we can create a new folder to place it in.
